#!/usr/bin/env bash

# redirect stdout/stderr to a file
#exec &> 
command | tee -a /var/log/foreman/foreman_hyperv.log

##################################################################################Test script to develop foreman_hyperv rpm package. This script comes with#### ##now guarentees of any kind. Use at your own risk.###
##This MUST be ran with root permissions.###
###############################################################################


yum deplist [rubygem-gssapi.noarch] [ruby-devel] [rubygems-devel.noarch] [gcc-toolset-10] [perl-NTLM.noarch] [libntlm-devel] [libntlm gssntlmssp] [rubygem-httpclient] [puppet-bolt] [rubygem-rb-inotify.noarch] [rubygem-openscap.noarch] [Development Tools] [.NET Core Development]

dnf -y install rubygem-gssapi.noarch ruby-devel rubygems-devel.noarch gcc-toolset-10 perl-NTLM.noarch libntlm-devel libntlm gssntlmssp rubygem-httpclient rubygem-rb-inotify.noarch rubygem-openscap.noarch puppet-bolt

dnf -y groupinstall 'Development Tools' '.NET Core Development'

scl enable gcc-toolset-10 -- gem install gyoku --ignore-dependencies

scl enable gcc-toolset-10 -- gem install nori --ignore-dependencies 

scl enable gcc-toolset-10 -- gem install rubyntlm --ignore-dependencies

scl enable gcc-toolset-10 -- gem install winrm --ignore-dependencies

scl enable gcc-toolset-10 -- gem install ffi --ignore-dependencies

scl enable gcc-toolset-10 -- gem install foreman_hyperv --ignore-dependencies

scl enable gcc-toolset-10 -- gem install fog-hyperv 

touch /usr/share/foreman/bundler.d/foreman_hyperv.rb

echo "gem 'foreman_hyperv' 
gem 'gssapi'
gem 'ffi'
gem 'gyoku'
gem 'nori'
gem 'fog-hyperv'
gem 'httpclient'
gem 'rubyntlm'
gem 'little-plugger'
gem 'winrm'" > /usr/share/foreman/bundler.d/foreman_hyperv.rb

echo "System will be rebooted for changes to take effect. Enter 'shutdown -a' to abort reboot."

sleep "20s"

echo "Restartng now"

systemctl reboot


